sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t antonioalmeidab/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true antonioalmeidab/docker-react npm run test